In [1]:
import pandas as pd

In [19]:
df = pd.read_csv("final_data_with_form_name.csv")

/var/folders/qd/53v0q6g93r5g_dc_bwl8_tlw0000gn/T/ipykernel_3950/1125918065.py:1: DtypeWarning: Columns (8,15,16) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("final_data_with_form_name.csv")

In [20]:
df.sample(2)

,Company Name,NAIC Company Code,Insurance Product Name,Sub Type Of Insurance,Filing Type,Filing Status,SERFF Tracking Number,Page Number,serf_num,state,page_url,form,auth_url,file_name,attachment_type,number_of_pages,readability_score,form_name
3418278,"Health Care Service Corporation, a Mutual Lega...",70670.0,BCBSNM Individual PPO,H16I.005A Individual - Preferred Provider (PPO),Form/Rate,Closed - Approved Certified,NWMC-129449983,70,129449983,NM,https://filingaccess.serff.com/sfa/search/fili...,True,https://filingaccess.serff.com/sfa/home/NM,SBC_2015_NM_Ind_Blue_PPO_Gold_002_OnEx_NA_LIMI...,form_attachments,10,NaN,NaN
4703640,Principal Life Insurance Company,61271.0,Dental PPO,Dental (H10.000),Other - Informational,Closed - Filed,USPH-6L5QJC333/00-00/00-00/00,171,6L5QJC333/00,IL,https://filingaccess.serff.com/sfa/search/fili...,True,https://filingaccess.serff.com/sfa/home/IL,rpt-providers0106.pdf,supporting_document_attachments,3,NaN,Response to problem report dated 1-

In [41]:
df[(df.readability_score.notna()) & (df.form_name.apply(lambda x: "read" not in (str(x).lower())))]

,Company Name,NAIC Company Code,Insurance Product Name,Sub Type Of Insurance,Filing Type,Filing Status,SERFF Tracking Number,Page Number,serf_num,state,page_url,form,auth_url,file_name,attachment_type,number_of_pages,readability_score,form_name
19,AAA Life Insurance Company,71854.0,Member Loyalty Travel Accident,H03I.000 Health - Accidental Death & Dismember...,Form,Closed - Approved,AAAL-125126788,1,125126788,AR,https://filingaccess.serff.com/sfa/search/fili...,True,https://filingaccess.serff.com/sfa/home/AR,AAAMLTENDCERT Readability Certification.pdf,supporting_document_attachments,1,43%,Certification/Notice
23,AAA Life Insurance Company,71854.0,Member Loyalty Travel Accident,Group Accident Only,Form,Closed - Approved,AAAL-125129644,1,125129644,CT,https://filingaccess.serff.com/sfa/search/fili...,True,https://filingaccess.serff.com/sfa/home/CT,MLTA AE Readability Certification.pdf,supporting_document_attachments,1,43%,Health Filings
38,AAA Life Insurance Company,71854.0,MLTA Endorsement,H03G.000 Health - Accidental Death & Dismember...,Form,Closed - Approved,AAAL-125152031,1,125152031,VA,https://filingaccess.serff.com/sfa/search/fili...,True,https://filingaccess.serff.com/sfa/home/VA,AAAMLTENDCERT.pdf,form_attachments,1,43.0,AAAMLTENDCERT
73,AAA Life Insurance Company,71854.0,MLTA Endorsement,H03G.000 Health - Accidental Death & Dismember...,Form,Closed - Approved,AAAL-125155261,1,125155261,OK,https://filingaccess.serff.com/sfa/search/fili...,True,https://filingaccess.serff.com/sfa/home/OK,AAAMLTENDCERT.pdf,form_attachments,1,43.0,AAAMTLENDCERT
147,AAA Life Insurance Company,71854.0,MLTA Amendatory Endorsement,Group Accidental Death & Dismemberment,Form,Closed - Approved,AAAL-125180909,1,125180909,IN,https://filingaccess.serff.com/sfa/search/fili...,True,https://filingaccess.serff.com/sfa/home/IN,AAAMLTENDCERT.pdf,form_attachments,1,43.0,AAAMLTENDCERT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4883689,Zurich American Life Insurance Company,90557.0,Group Disability,H11G.005 Combined Short Term and Long Term,Form,Closed - Disapproved,ZUUG-132476346,138,132476346,AR,https://filingaccess.serff.com/sfa/search/fili...,True,https://filingaccess.serff.com/sfa/home/AR,ZALIC-MQD-3 Musculoskeletal Questionnaire 5-3-...,form_attachments,2,50.0,Application
4883690,Zurich American Life Insurance Company,90557.0,Group Disability,H11G.005 Combined Short Term and Long Term,Form,Closed - Disapproved,ZUUG-132476346,138,132476346,AR,https://filingaccess.serff.com/sfa/search/fili...,True,https://filingaccess.serff.com/sfa/home/AR,ZALIC-MQD-6 Seizure Disorder Questionnaire 5-3...,form_attachments,2,50.0,Application
4883691,Zurich American Life Insurance Company,90557.0,Group Disability,H11G.005 Combined Short Term and Long Term,Form,Closed - Disapproved,ZUUG-132476346,138,132476346,AR,https://filingaccess.serff.com/sfa/search/fili...,True,https://filingaccess.serff.com/sfa/home/AR,ZALIC-MQD-5 Skin Cancer Quest (5-3-20).pdf,form_attachments,2,50.0,Application
4883692,Zurich American Life Insurance Company,90557.0,Group Disability,H11G.005 Combined Short Term and Long Term,Form,Closed - Disapproved,ZUUG-132476346,138,132476346,AR,https://filingaccess.serff.com/sfa/search/fili...,True,https://filingaccess.serff.com/sfa/home/AR,ZALIC-MQD-4 Cardiac Arrhythmia Questionnaire (...,form_attachments,2,50.0,Application
4883693,Zurich American Life Insurance Company,90557.0,Group Disability,H11G.005 Combined Short Term and Long Term,Form,Closed - Disapproved,ZUUG-132476346,138,132476346,AR,https://filingaccess.serff.com/sfa/search/fili...,True,https://filingaccess.serff.com/sfa/home/AR,ZALIC-MQD-2 Diabetes Questionnaire 5.3.20.pdf,form_attachments,2,50.0,Application

In [ ]:
df.

In [25]:
df[['SERFF Tracking Number', 'state', 'file_name', 'attachment_type', 'number_of_pages',
       'readability_score', 'form_name']]

,SERFF Tracking Number,state,file_name,attachment_type,number_of_pages,readability_score,form_name
0,AAAL-125053950,RI,Trust Agreement.pdf,supporting_document_attachments,5,NaN,Trust Documents
1,AAAL-125053950,RI,Group Ins[1].Ck.list1.pdf,supporting_document_attachments,2,NaN,Health Insurance Checklist
2,AAAL-125053950,RI,Statement of Rates.pdf,supporting_document_attachments,1,NaN,Premium Rate Sheets - Life & A&H
3,AAAL-125053950,RI,Actuarial Certification.pdf,supporting_document_attachments,1,NaN,Actuarial Certification - Life & A&H
4,AAAL-125053950,RI,Amended and Restated Trust for the AAA Group I...,supporting_document_attachments,4,NaN,NaN
...,...,...,...,...,...,...,...
4883710,ZUUG-132507564,MO,Ferrellgas ADL and Limited Benefits Endorsemen...,supporting_document_attachments,4,NaN,NaN
4883711,ZUUG-132507564,MO,ZALIC-FER-01-01 Endorsement SOV (9-14-20) Redl...,supporting_document_attachments,1,NaN,Red-lined Endorsement
4883712,ZUUG-132507564,MO,ZALIC-FER-01-01 Endorsement SOV (9-14-20) fina...,supporting_document_attachments,1,NaN,Statement of Variability
4883713,ZUUG-134054739,MI,Grievance Report - FIS_0318 Rep Year 2023.pdf,supporting_document_attachments,2,NaN,Summary Form
4883714,ZUUG-134491160,MI,FIS_0318 (11-24) signed.pdf,supporting_document_attachments,2,NaN,Summary Form

In [21]:
old_data = pd.read_csv("data_with_flesh_score_complete_set.csv")

/var/folders/qd/53v0q6g93r5g_dc_bwl8_tlw0000gn/T/ipykernel_3950/3325111460.py:1: DtypeWarning: Columns (8) have mixed types. Specify dtype option on import or set low_memory=False.
  old_data = pd.read_csv("data_with_flesh_score_complete_set.csv")

In [22]:
old_data.shape

(2286347, 17)

In [23]:
old_data.sample(3)

,Company Name,NAIC Company Code,Insurance Product Name,Sub Type Of Insurance,Filing Type,Filing Status,SERFF Tracking Number,Page Number,serf_num,state,page_url,form,auth_url,form_name,submission_date,flesch_reading_ease,serf_int
853852,ACE American Insurance Company,22667.0,Group Hospital Indemnity Policy,H14G.000 Health - Hospital Indemnity,Form,Closed - Approved,ACEH-129921659,1,129921659,CT,https://filingaccess.serff.com/sfa/search/fili...,True,https://filingaccess.serff.com/sfa/home/CT,Group Hospital Indemnity Certificate,2/11/15,36.358579,129921659.0
2164216,Zurich American Insurance Company,16535.0,Zurich Accident for Groups (ZAG),H02G.000 Health - Accident Only,Form/Rate,Closed - Approved,ZURC-134485595,79,134485595,NV,https://filingaccess.serff.com/sfa/search/fili...,True,https://filingaccess.serff.com/sfa/home/NV,Outpatient Physician’s Treatment Benefit,4/16/25,35.108891,134485595.0
1984589,American Family Life Assurance Company of Colu...,60380.0,AFLAC Group Dental PPO,H10G.000 Health - Dental,Form/Rate,Closed - Approved,AFLA-133768612,6,133768612,NM,https://filingaccess.serff.com/sfa/search/fili...,True,https://filingaccess.serff.com/sfa/home/NM,Dental Rate Manual,8/3/23,71.988023,133768612.0

In [27]:
old_data.shape

(2286347, 17)

In [50]:
old_data.columns

Index(['Company Name', 'NAIC Company Code', 'Insurance Product Name',
       'Sub Type Of Insurance', 'Filing Type', 'Filing Status',
       'SERFF Tracking Number', 'Page Number', 'serf_num', 'state', 'page_url',
       'form', 'auth_url', 'form_name', 'submission_date',
       'flesch_reading_ease', 'serf_int'],
      dtype='object')

In [53]:
export_df = old_data[['SERFF Tracking Number', 'serf_num', 'state', 'page_url','form', 'auth_url',]]
export_df.drop_duplicates(inplace=True)
export_df.to_csv("old_data_from_name_fetch.csv",index=False)

/var/folders/qd/53v0q6g93r5g_dc_bwl8_tlw0000gn/T/ipykernel_3950/3839639682.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  export_df.drop_duplicates(inplace=True)

In [74]:

outputs = "../outputs/"

processed_files = [
    os.path.join(outputs, f)
    for f in os.listdir(outputs)
    if f.endswith(".csv")
]

In [79]:
import os
import pandas as pd

folder = "new_outputs/read_page/outputs"

csv_files = [
    os.path.join(folder, f)
    for f in os.listdir(folder)
    if f.endswith(".csv")
]

csv_files+=processed_files

already_completed = pd.concat(
    [pd.read_csv(f) for f in csv_files],
    ignore_index=True
)

In [83]:
already_completed.dropna(subset="form_name_mapping",inplace=True)

In [84]:
already_completed.shape

(102969, 15)

In [85]:
export_df2 = export_df[~export_df['SERFF Tracking Number'].isin(already_completed["SERFF Tracking Number"])]
export_df2 = export_df2[export_df2['SERFF Tracking Number'].isin(df[df.readability_score.notna()]["SERFF Tracking Number"])]

export_df2.to_csv("../data/old_data_from_name_fetch_3.csv",index=False)

In [86]:
export_df2.shape

(59271, 6)

In [89]:
export_df2[export_df2['serf_num']=="6UAHR6436/00"].values

array([['USPH-6UAHR6436/00-00/00-00/00', '6UAHR6436/00', 'SD',
        'https://filingaccess.serff.com/sfa/search/filingSummary.xhtml?filingId=6UAHR6436/00',
        True, 'https://filingaccess.serff.com/sfa/home/SD']], dtype=object)

In [49]:
old_data.drop_duplicates(subset=['SERFF Tracking Number','form_name'])

,Company Name,NAIC Company Code,Insurance Product Name,Sub Type Of Insurance,Filing Type,Filing Status,SERFF Tracking Number,Page Number,serf_num,state,page_url,form,auth_url,form_name,submission_date,flesch_reading_ease,serf_int
0,John Alden Life Insurance Company,65080.0,John Alden-Base Chassis,H16G.003A Small Group Only - PPO,Form,Closed - Approved,SPIN-0061UX076/00-00/00-00/00,47,0061UX076/00,IA,https://filingaccess.serff.com/sfa/search/fili...,True,https://filingaccess.serff.com/sfa/home/IA,NaN,2/21/06,NaN,NaN
1,Union Security Insurance Company,70408.0,USIC-2500P Union Security Disability Income,Group Disability Income,Form,Closed - Closed Exempt,SPIN-00F104005/00-00/00-00/00,120,00F104005/00,SC,https://filingaccess.serff.com/sfa/search/fili...,True,https://filingaccess.serff.com/sfa/home/SC,NaN,7/13/06,NaN,NaN
2,John Alden Life Insurance Company,65080.0,John Alden-Base Chassis,H16I.005C Individual - Other,Health New Form Review,Closed - (ONO)Closed File /Final Action,SPIN-02DS0UG6J/00-00/00-00/00,116,02DS0UG6J/00,NC,https://filingaccess.serff.com/sfa/search/fili...,True,https://filingaccess.serff.com/sfa/home/NC,NaN,3/31/06,NaN,NaN
3,StarNet Insurance Company,40045.0,AH51041 StarNet Provider Excess Loss Policy,Other,Form,Closed - Approved,SPIN-02K1C116B/00-00/00-00/00,75,02K1C116B/00,VT,https://filingaccess.serff.com/sfa/search/fili...,True,https://filingaccess.serff.com/sfa/home/VT,NaN,8/30/06,NaN,NaN
4,John Alden Life Insurance Company,65080.0,John Alden-Base Chassis,Individual AH Major Medical(876),Form/Rate/Rule,Closed - DISAPPROVED,SPIN-037AKKLGG/00-00/00-00/00,83,037AKKLGG/00,ID,https://filingaccess.serff.com/sfa/search/fili...,True,https://filingaccess.serff.com/sfa/home/ID,NaN,10/26/05,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2286342,Fortis Benefits Insurance Company,70408.0,FB - EM2K Form Filing,H16G.001C Any Size Group - Other,Form,Closed - Approved,SPIN-YF8GI4YM3/00-00/00-00/00,34,YF8GI4YM3/00,SD,https://filingaccess.serff.com/sfa/search/fili...,True,https://filingaccess.serff.com/sfa/home/SD,NaN,3/17/05,NaN,NaN
2286343,John Alden Life Insurance Company,65080.0,JA - 145 Form Filing True,Short Term Contracts(894),Form/Rate,Closed - FILED,SPIN-YG5D46015/00-00/00-00/00,83,YG5D46015/00,ID,https://filingaccess.serff.com/sfa/search/fili...,True,https://filingaccess.serff.com/sfa/home/ID,NaN,4/4/06,NaN,NaN
2286344,John Alden Life Insurance Company,65080.0,8067 JALIC Indiv Hosp Confinement & Sickness I...,H14I.000 Health - Hospital Indemnity,Form and Rate,Closed - FILED FOR USE,SPIN-YH7T5F6QU/00-00/00-00/00,51,YH7T5F6QU/00,UT,https://filingaccess.serff.com/sfa/search/fili...,True,https://filingaccess.serff.com/sfa/home/UT,NaN,5/4/06,NaN,NaN
2286345,Time Insurance Company,69477.0,8033 TIC Indiv Critical Illness Cancer,Specified Disease (24),Form,Closed - Approved,SPIN-YK3O61GQ8/00-00/00-00/00,157,YK3O61GQ8/00,OK,https://filingaccess.serff.com/sfa/search/fili...,True,https://filingaccess.serff.com/sfa/home/OK,NaN,4/28/06,NaN,NaN
2286346,New York Life Insurance Company,66915.0,ILTC-5000 Select Premier,Individual AH Long Term Care(889),Form,Closed - FILED,SPIN-YQ83822Q6/00-00/00-00/00,108,YQ83822Q6/00,ID,https://filingaccess.serff.com/sfa/search/fili...,True,https://filingaccess.serff.com/sfa/home/ID,NaN,6/15/06,NaN,NaN

In [30]:
result_1 = pd.merge(old_data[old_data.form_name.notna()],df[['SERFF Tracking Number', 'file_name', 'attachment_type', 'number_of_pages',
       'readability_score', 'form_name']],on=['SERFF Tracking Number','form_name'])

In [34]:
result_1[result_1.readability_score.notna()].to_csv("file_mapped_with_readability_score.csv",index=False)

In [44]:
result_1[result_1.readability_score.notna()].shape

(72233, 21)

In [45]:
result_1.shape

(593309, 21)

In [48]:
result_1[result_1.readability_score.notna()]

,Company Name,NAIC Company Code,Insurance Product Name,Sub Type Of Insurance,Filing Type,Filing Status,SERFF Tracking Number,Page Number,serf_num,state,...,form,auth_url,form_name,submission_date,flesch_reading_ease,serf_int,file_name,attachment_type,number_of_pages,readability_score
16,Bankers Life and Casualty Company,61263.0,GR-N560 Convalescent Care,H13I.002 Nursing Home,Form/Rate,Closed - Disapproved,BNLA-125000985,16,125000985,SD,...,True,https://filingaccess.serff.com/sfa/home/SD,GR-N565Rate,11/8/06,63.853610,125000985.0,N565_SD.pdf,rate_rule_attachments,8,55.52
17,Bankers Life and Casualty Company,61263.0,GR-N560 Convalescent Care,H13I.002 Nursing Home,Form/Rate,Closed - Disapproved,BNLA-125000985,16,125000985,SD,...,True,https://filingaccess.serff.com/sfa/home/SD,GR-N560Rate,11/8/06,65.460028,125000985.0,N560_SD.pdf,rate_rule_attachments,8,56.86
18,Bankers Life and Casualty Company,61263.0,GR-N560 Convalescent Care,H13I.002 Nursing Home,Form/Rate,Closed - Disapproved,BNLA-125000985,16,125000985,SD,...,True,https://filingaccess.serff.com/sfa/home/SD,17300,11/8/06,41.906060,125000985.0,17300.pdf,form_attachments,5,51.86
19,Bankers Life and Casualty Company,61263.0,GR-N560 Convalescent Care,H13I.002 Nursing Home,Form/Rate,Closed - Disapproved,BNLA-125000985,16,125000985,SD,...,True,https://filingaccess.serff.com/sfa/home/SD,15897,11/8/06,28.475411,125000985.0,15897SD.pdf,form_attachments,4,45.31
20,Bankers Life and Casualty Company,61263.0,GR-N560 Convalescent Care,H13I.002 Nursing Home,Form/Rate,Closed - Disapproved,BNLA-125000985,16,125000985,SD,...,True,https://filingaccess.serff.com/sfa/home/SD,15896,11/8/06,32.108928,125000985.0,15896SD.pdf,form_attachments,3,48.78
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
592976,Oakwood Insurance Company,31208.0,Oakwood Group Stop Loss,H12.001 Accident & Sickness,Form,Received,LWEL-134710951,26,134710951,KY,...,True,https://filingaccess.serff.com/sfa/home/KY,Policy,10/21/25,32.610631,134710951.0,OIC-SL-25-1000KY Policy.pdf,form_attachments,21,50.2
592977,Oakwood Insurance Company,31208.0,Oakwood Group Stop Loss,H12.001 Accident & Sickness,Form,Received,LWEL-134710951,26,134710951,KY,...,True,https://filingaccess.serff.com/sfa/home/KY,Application,10/21/25,22.478103,134710951.0,OIC-SL-25-5000KY Application .pdf,form_attachments,4,50.2
593301,National Union Fire Insurance Company of Pitts...,19445.0,S30406NUFIC (Rev. 7/11) Blanket Accident - Nat...,H04.000 Health - Blanket Accident/Sickness,Form/Rate,Closed - (APP)Form Approval,MCHX-G128715543,145,G128715543,NC,...,True,https://filingaccess.serff.com/sfa/home/NC,B-2 Trip Delay Benefit Rider,10/9/12,26.062142,NaN,S30599NUFIC-NC clean 2-1a-13.pdf,form_attachments,4,51.8
593302,National Union Fire Insurance Company of Pitts...,19445.0,S30406NUFIC (Rev. 7/11) Blanket Accident - Nat...,H04.000 Health - Blanket Accident/Sickness,Form/Rate,Closed - (APP)Form Approval,MCHX-G128715543,145,G128715543,NC,...,True,https://filingaccess.serff.com/sfa/home/NC,B-2 Trip Delay Benefit Rider,10/9/12,26.109246,NaN,S30599NUFIC-NC clean 2-1a-13.pdf,form_attachments,4,51.8
593303,National Union Fire Insurance Company of Pitts...,19445.0,S30406NUFIC (Rev. 7/11) Blanket Accident - Nat...,H04.000 Health - Blanket Accident/Sickness,Form/Rate,Closed - (APP)Form Approval,MCHX-G128715543,145,G128715543,NC,...,True,https://filingaccess.serff.com/sfa/home/NC,B-2 Trip Delay Benefit Rider,10/9/12,25.816784,NaN,S30599NUFIC-NC clean 2-1a-13.pdf,form_attachments,4,51.8